### ISSUE TITLE
小米电视 MiTV OS 2.0.1 无法正常投屏

### ISSUE THREAD

**Issue by xperezxin** [duolabmeng6/projection_screen_tv#1]
### 新版本 v0.0.7
- 点击投屏，出现下载较慢，或者卡在投屏过程中
- 点击“开始播放”，出现“已发送播放指令”电视上无任何响应
![image](https://github.com/duolabmeng6/projection_screen_tv/assets/31504184/532aed98-5d34-4c09-bfd4-cba6c918967d)

### 老版本正常 v0.1.20
- 老版本本地文件和链接均播放正常

**Comment by duolabmeng6** [comment]
我以前是用python开发的 投屏协议 这次是golang的 我测试一下看看是什么问题
